### PR TITLE
Switch keystone plugin to meson

### PR DESCRIPTION
**Pull request by ret2libc**

### CODE REVIEW

**Review by wargio — APPROVED** [review]

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
What about removing old Makefiles then?

**Comment by ret2libc** [comment]
> What about removing old Makefiles then?

I would use the same "grace period" we are using in rizin. So we are going to remove makefiles at some point in the next releases. Does that sound good?

**Comment by XVilka** [comment]
Isn't this ready to merge @ret2libc ?

**Comment by ret2libc** [comment]
It is, merged.

**Pull request merged**
